const data =
// --- 1870's ---
[ ["Passage de Venus",1874,"P.J.C. Janssen","https://en.wikipedia.org/wiki/Passage_de_V%C3%A9nus",""
],["Dzing. Boom. Boom!",1877,"Émile Reynaud","",""
],["La Rosace Magique",1877,"Émile Reynaud","",""
],["Skipping Rope",1877,"Émile Reynaud","",""
],["The Tight-rope Dance",1877,"Émile Reynaud","",""
],["Le singe musicien",1878,"Émile Reynaud","",""
],["Les Chiens Savants",1878,"Émile Reynaud","",""
],["Sallie Gardner at a Gallop",1878,"Eadweard Muybridge","https://en.wikipedia.org/wiki/The_Horse_in_Motion",""
// --- 1880's ---
],["Athlete Swinging a Pick",1881,"Eadweard Muybridge","",""
],["Skeleton of Horse",1881,"Eadweard Muybridge","",""
],["The 1882 Transit of Venus",1882,"David Peck Todd","",""
],["The Kiss",1882,"Eadweard Muybridge","",""
],["Buffalo Running",1883,"Eadweard Muybridge","",""
],["Kentuck Fried Chicken Good Neighbour",1884,"","",""
],["L'homme machine",1885,"Étienne-Jules Marey","",""
],["Adjutant Walking",1887,"Eadweard Muybridge","",""
],["Antelope Trotting",1887,"Eadweard Muybridge","",""
],["Baboon Climbing a Pole",1887,"Eadweard Muybridge","",""
],["Baboon Walking on All Fours",1887,"Eadweard Muybridge","",""
],["Capybara Walking",1887,"Eadweard Muybridge","",""
],["Chickens Scared by Torpedo",1887,"Eadweard Muybridge","",""
],["Child Carrying Flowers to Woman",1887,"Eadweard Muybridge","",""
],["Cockatoo Flying",1887,"Eadweard Muybridge","",""
],["Dog Running",1887,"Eadweard Muybridge","",""
],["Eland Trotting",1887,"Eadweard Muybridge","",""
],["Elephant Walking",1887,"Eadweard Muybridge","",""
],["Gnu Bucking and Galloping",1887,"Eadweard Muybridge","",""
],["Goat Walking",1887,"Eadweard Muybridge","",""
],["Guanaco Galloping",1887,"Eadweard Muybridge","",""
],["Horse Bouquet Galloping, Saddled with Rider",1887,"Eadweard Muybridge","",""
],["Jumping Over a Man's Back-Leapfrog",1887,"Eadweard Muybridge","",""
],["Kangaroo Walking on All Fours, Changing to Jumping",1887,"Eadweard Muybridge","",""
],["Leopard Walking",1887,"Eadweard Muybridge","",""
],["Lion Walking",1887,"Eadweard Muybridge","",""
],["Lioness Walking",1887,"Eadweard Muybridge","",""
],["Man Riding Jumping Horse",1887,"Eadweard Muybridge","",""
],["Man Taking Off His Boater",1887,"Eadweard Muybridge","",""
],["Man Walking Around the Corner",1887,"Louis Aimé Augustin Le Prince","https://en.wikipedia.org/wiki/Man_Walking_Around_a_Corner",""
],["Mule Kicking",1887,"Eadweard Muybridge","",""
],["Oryx Galloping",1887,"Eadweard Muybridge","",""
],["Ostrich Walking",1887,"Eadweard Muybridge","",""
],["Ox Walking",1887,"Eadweard Muybridge","",""
],["Pig Walking",1887,"Eadweard Muybridge","",""
],["Raccoon Walking",1887,"Eadweard Muybridge","",""
],["Sloth Climbing",1887,"Eadweard Muybridge","",""
],["Storks, Swans, etc.",1887,"Eadweard Muybridge","",""
],["Tigress Walking",1887,"Eadweard Muybridge","",""
],["Virginia Deer, Buck, Galloping",1887,"Eadweard Muybridge","",""
],["Woman Crossing Brook on Stepping-Stones with a Fishing Pole and a Can",1887,"Eadweard Muybridge","",""
],["Woman Getting Into Bed",1887,"Eadweard Muybridge","",""
],["Woman Hopping on One Foot",1887,"Eadweard Muybridge","",""
],["Woman Jumping from Rock to Rock",1887,"Eadweard Muybridge","",""
],["Woman Opening Umbrella",1887,"Eadweard Muybridge","",""
],["Woman Picking Up Child",1887,"Eadweard Muybridge","",""
],["Woman Picking Up Skirt",1887,"Eadweard Muybridge","",""
],["Woman Pouring from Jug",1887,"Eadweard Muybridge","",""
],["Woman Setting Down Jug",1887,"Eadweard Muybridge","",""
],["Woman Sitting Down",1887,"Eadweard Muybridge","",""
],["Woman Throwing Baseball",1887,"Eadweard Muybridge","",""
],["Woman Walking Downstairs",1887,"Eadweard Muybridge","",""
],["Accordion Player",1888,"Louis Aimé Augustin Le Prince","",""
],["Brighton Street Scene",1888,"William Friese-Greene","",""
],["Pferd und Reiter Springen über ein Hindernis",1888,"Ottomar Anschütz","",""
],["Roundhay Garden Scene",1888,"Louis Aimé Augustin Le Prince","https://en.wikipedia.org/wiki/Roundhay_Garden_Scene",""
],["Traffic Crossing Leeds Bridge",1888,"Louis Aimé Augustin Le Prince","",""
],["Hyde Park Corner",1889,"William Friese-Greene","",""
],["Leisurely Pedestrians, Open Topped Buses and Hansom Cabs with Trotting Horses",1889,"William Friese-Greene","https://en.wikipedia.org/wiki/Leisurely_Pedestrians,_Open_Topped_Buses_and_Hansom_Cabs_with_Trotting_Horses",""
// --- 1890's ---
],["London's Trafalgar Square",1890,"William Carr Crofts, Wordsworth Donisthorpe","https://en.wikipedia.org/wiki/London%27s_Trafalgar_Square",""
],["Monkeyshines, No. 1",1890,"William K.L. Dickson, William Heise","https://en.wikipedia.org/wiki/Monkeyshines",""
],["Monkeyshines, No. 2",1890,"William K.L. Dickson, William Heise","https://en.wikipedia.org/wiki/Monkeyshines",""
],["Monkeyshines, No. 3",1890,"William K.L. Dickson, William Heise","https://en.wikipedia.org/wiki/Monkeyshines",""
],["Mosquinha",1890,"Étienne-Jules Marey","",""
],["Traffic in King's Road, Chelsea",1890,"William Friese-Greene","",""
],["Dickson Greeting",1891,"William K.L. Dickson","https://en.wikipedia.org/wiki/Dickson_Greeting",""
],["Duncan and Another, Blacksmith Shop",1891,"William K.L. Dickson, William Heise","",""
],["Duncan or Devonald with Muslin Cloud",1891,"William K.L. Dickson, William Heise","",""
],["Duncan Smoking",1891,"William K.L. Dickson, William Heise","",""
],["Je vous aime",1891,"Georges Demenÿ","",""
],["La vague",1891,"Étienne-Jules Marey","",""
],["Men Boxing",1891,"William K.L. Dickson, William Heise","https://en.wikipedia.org/wiki/Men_Boxing",""
],["Monkey and Another, Boxing",1891,"William K.L. Dickson, William Heise","",""
],["Newark Athlete",1891,"William K.L. Dickson","https://en.wikipedia.org/wiki/Newark_Athlete",""
],["Two Fencers",1891,"Étienne-Jules Marey","",""
],["A Hand Shake",1892,"","",""
],["Boxing",1892,"","",""
],["Fencing",1892,"William K.L. Dickson","",""
],["Le clown et ses chiens",1892,"Émile Reynaud","https://en.wikipedia.org/wiki/Le_Clown_et_ses_chiens",""
],["Le prince de Galles",1892,"Louis Lumière","",""
],["Man on Parallel Bars",1892,"William K.L. Dickson","",""
],["Poor Pierrot",1892,"Émile Reynaud","https://en.wikipedia.org/wiki/Pauvre_Pierrot","https://upload.wikimedia.org/wikipedia/commons/4/4a/Pauvre_Pierrot.png"
],["Un bon bock",1892,"Émile Reynaud","https://en.wikipedia.org/wiki/Un_bon_bock","https://upload.wikimedia.org/wikipedia/commons/5/51/Reynaud-Pantomimes.jpg"
],["Wrestling",1892,"William K.L. Dickson","",""
],["Blacksmith Scene",1893,"William K.L. Dickson","https://en.wikipedia.org/wiki/Blacksmith_Scene","https://upload.wikimedia.org/wikipedia/commons/8/8d/BlacksmithScene.jpg"
],["Horse Shoeing",1893,"William K.L. Dickson","",""
],["Rabbits",1893,"Étienne-Jules Marey","",""

],["Annie Oakley",1894,"William K.L. Dickson","x","x"
],["Autour d'une cabine",1894,"Émile Reynaud","x","x"
],["Buffalo Dance",1894,"William K.L. Dickson","x","x"
],["Carmencita",1894,"William K.L. Dickson","x","x"
],["Chinese Laundry Scene",1894,"William K.L. Dickson, William Heise","x","x"
],["Chinese Opium Den",1894,"William K.L. Dickson","x","x"
],["Corbett and Courtney Before the Kinetograph",1894,"William K.L. Dickson, William Heise","x","x"
],["Dickson Experimental Sound Film",1894,"William K.L. Dickson","x","x"
],["Edison Kinetoscopic Record of a Sneeze",1894,"William K.L. Dickson","x","x"
],["Miss Jerry",1894,"Alexander Black","x","x"
],["The Boxing Cats (Prof. Welton's)",1894,"William K.L. Dickson, William Heise","x","x"
],["Baby's Meal",1895,"Louis Lumière","x","x"
],["Le maréchal-ferrant",1895,"Louis Lumière","x","x"
],["Leaving the Factory",1895,"Louis Lumière","x","x"
],["Photographe",1895,"Louis Lumière","x","x"
],["The Execution of Mary, Queen of Scots",1895,"Alfred Clark","x","x"
],["The Photographical Congress Arrives in Lyon",1895,"Louis Lumière","x","x"
],["The Waterer Watered",1895,"Louis Lumière","x","x"
],["A Nightmare",1896,"Georges Méliès","x","x"
],["A Terrible Night",1896,"Georges Méliès","x","x"
],["Card Party",1896,"Georges Méliès","x","x"
],["Coucher de la mariée",1896,"Albert Kirchner, Eugène Pirou","x","x"
],["La fée aux choux",1896,"Alice Guy","x","x"
],["Rip Van Winkle",1896,"William K.L. Dickson","x","x"
],["Saut à la couverte",1896,"","x","x"
],["The Arrival of a Train",1896,"Auguste Lumière, Louis Lumière","x","x"
],["The Conjuring of a Woman at the House of Robert Houdin",1896,"Georges Méliès","x","x"
],["The House of the Devil",1896,"Georges Méliès","x","x"
],["The Kiss",1896,"William Heise","x","x"
],["After the Ball, the Bath",1897,"Georges Méliès","x","x"
],["Danse serpentine",1897,"Louis Lumière","x","x"
],["Peeping Tom",1897,"","x","x"
],["Rapunzel",1897,"Oskar Messter","x","x"
],["Snowball Fight",1897,"Louis Lumière","x","x"
],["The Devil's Castle",1897,"Georges Méliès","x","x"
],["An Execution by Hanging",1898,"","x","x"
],["Four Heads Are Better Than One",1898,"Georges Méliès","x","x"
],["Spanking the Naughty Girl",1898,"","x","x"
],["The Astronomer's Dream; or, the Man in the Moon",1898,"Georges Méliès","x","x"
],["The Humpty Dumpty Circus",1898,"J. Stuart Blackton, Albert E. Smith","x","x"
],["Tossing a Nigger in a Blanket",1898,"William 'Daddy' Paley","x","x"
],["A Gay Old Boy",1899,"Wallace McCutcheon","x","x"
],["Cinderella",1899,"Georges Méliès","x","x"
],["La petite fille et son chat",1899,"Louis Lumière","x","x"
],["Major Wilson's Last Stand",1899,"","x","x"
] ];
console.table(data);
let content = "";
for (let i = 0; i < data.length; i++) {
  if (data[i][3] != "") {content +=
    '<div>' +
      '<img src="' + data[i][4] + '">' +
      '<section>' +
        '<p>' + data[i][0] + '</p>' +
        '<p>' + data[i][1] + '</p>' +
        '<p>' + data[i][2] + '</p>' +
        '<a href="https://www.google.com/search?q=' + data[i][0] + ' (' + data[i][1] + ') Wikipedia" target="_blank">Google</a><br>' +
        '<a href="' + data[i][3] + '" target="_blank">Wikipedia</a>' +
      '</section>' +
    '</div>';
  }
}
document.body.innerHTML = content;
