const data =
// --- 1870's ---
[ ["Passage de Venus",1874,"P.J.C. Janssen","https://en.wikipedia.org/wiki/Passage_de_V%C3%A9nus",""
],["Dzing. Boom. Boom!",1877,"Émile Reynaud","",""
],["La Rosace Magique",1877,"Émile Reynaud","",""
],["Skipping Rope",1877,"Émile Reynaud","",""
],["The Tight-rope Dance",1877,"Émile Reynaud","",""
],["Le singe musicien",1878,"Émile Reynaud","",""
],["Les Chiens Savants",1878,"Émile Reynaud","",""
],["Sallie Gardner at a Gallop",1878,"Eadweard Muybridge","https://en.wikipedia.org/wiki/The_Horse_in_Motion",""
// --- 1880's ---
],["Athlete Swinging a Pick",1881,"Eadweard Muybridge","",""
],["Skeleton of Horse",1881,"Eadweard Muybridge","",""
],["The 1882 Transit of Venus",1882,"David Peck Todd","",""
],["The Kiss",1882,"Eadweard Muybridge","",""
],["Buffalo Running",1883,"Eadweard Muybridge","",""
],["L'homme machine",1885,"Étienne-Jules Marey","",""
],["Adjutant Walking",1887,"Eadweard Muybridge","",""
],["Antelope Trotting",1887,"Eadweard Muybridge","",""
],["Baboon Climbing a Pole",1887,"Eadweard Muybridge","",""
],["Baboon Walking on All Fours",1887,"Eadweard Muybridge","",""
],["Capybara Walking",1887,"Eadweard Muybridge","",""
],["Child Carrying Flowers to Woman",1887,"Eadweard Muybridge","",""
],["Cockatoo Flying",1887,"Eadweard Muybridge","",""
],["Dog Running",1887,"Eadweard Muybridge","",""
],["Eland Trotting",1887,"Eadweard Muybridge","",""
],["Elephant Walking",1887,"Eadweard Muybridge","",""
],["Guanaco Galloping",1887,"Eadweard Muybridge","",""
],["Horse Bouquet Galloping, Saddled with Rider",1887,"Eadweard Muybridge","",""
],["Jumping Over a Man's Back-Leapfrog",1887,"Eadweard Muybridge","",""
],["Kangaroo Walking on All Fours, Changing to Jumping",1887,"Eadweard Muybridge","",""
],["Lion Walking",1887,"Eadweard Muybridge","",""
],["Lioness Walking",1887,"Eadweard Muybridge","",""
],["Man Riding Jumping Horse",1887,"Eadweard Muybridge","",""
],["Man Walking Around the Corner",1887,"Louis Aimé Augustin Le Prince","https://en.wikipedia.org/wiki/Man_Walking_Around_a_Corner",""
],["Mule Kicking",1887,"Eadweard Muybridge","",""
],["Oryx Galloping",1887,"Eadweard Muybridge","",""
],["Ox Walking",1887,"Eadweard Muybridge","",""
],["Raccoon Walking",1887,"Eadweard Muybridge","",""
],["Sloth Climbing",1887,"Eadweard Muybridge","",""
],["Storks, Swans, etc.",1887,"Eadweard Muybridge","",""
],["Tigress Walking",1887,"Eadweard Muybridge","",""
],["Virginia Deer, Buck, Galloping",1887,"Eadweard Muybridge","",""
],["Woman Crossing Brook on Stepping-Stones with a Fishing Pole and a Can",1887,"Eadweard Muybridge","",""
],["Woman Getting Into Bed",1887,"Eadweard Muybridge","",""
],["Woman Hopping on One Foot",1887,"Eadweard Muybridge","",""
],["Woman Jumping from Rock to Rock",1887,"Eadweard Muybridge","",""
],["Woman Opening Umbrella",1887,"Eadweard Muybridge","",""
],["Woman Picking Up Child",1887,"Eadweard Muybridge","",""
],["Woman Pouring from Jug",1887,"Eadweard Muybridge","",""
],["Woman Setting Down Jug",1887,"Eadweard Muybridge","",""
],["Woman Sitting Down",1887,"Eadweard Muybridge","",""
],["Woman Walking Downstairs",1887,"Eadweard Muybridge","",""
],["Accordion Player",1888,"Louis Aimé Augustin Le Prince","",""
],["Brighton Street Scene",1888,"William Friese-Greene","",""
],["Pferd und Reiter Springen über ein Hindernis",1888,"Ottomar Anschütz","",""
],["Roundhay Garden Scene",1888,"Louis Aimé Augustin Le Prince","https://en.wikipedia.org/wiki/Roundhay_Garden_Scene",""
],["Traffic Crossing Leeds Bridge",1888,"Louis Aimé Augustin Le Prince","",""
],["Hyde Park Corner",1889,"William Friese-Greene","",""
],["Leisurely Pedestrians, Open Topped Buses and Hansom Cabs with Trotting Horses",1889,"William Friese-Greene","https://en.wikipedia.org/wiki/Leisurely_Pedestrians,_Open_Topped_Buses_and_Hansom_Cabs_with_Trotting_Horses",""
// --- 1890's ---
],["Monkeyshines, No. 1",1890,"William K.L. Dickson, William Heise","https://en.wikipedia.org/wiki/Monkeyshines","x"
],["Newark Athlete",1891,"William K.L. Dickson","x","x"
],["Le clown et ses chiens",1892,"Émile Reynaud","x","x"
],["Poor Pierrot",1892,"Émile Reynaud","x","x"
],["Un bon bock",1892,"Émile Reynaud","x","x"
],["Blacksmith Scene",1893,"William K.L. Dickson","x","x"
],["Carmencita",1894,"William K.L. Dickson","x","x"
],["Chinese Laundry Scene",1894,"William K.L. Dickson, William Heise","x","x"
],["Chinese Opium Den",1894,"William K.L. Dickson","x","x"
],["Falling Cat",1894,"Étienne-Jules Marey","x","x"
],["Miss Jerry",1894,"Alexander Black","x","x"
],["The Boxing Cats (Prof. Welton's)",1894,"William K.L. Dickson, William Heise","x","x"
],["Baby's Meal",1895,"Louis Lumière","x","x"
],["Boat Leaving the Port",1895,"Louis Lumière","x","x"
],["Fishing for Goldfish",1895,"Louis Lumière","x","x"
],["Le déjeuner du chat",1895,"Louis Lumière","x","x"
],["Leaving the Factory",1895,"Louis Lumière","x","x"
],["The Execution of Mary, Queen of Scots",1895,"Alfred Clark","x","x"
],["The Mechanical Butcher",1895,"Louis Lumière","x","x"
],["The Photographical Congress Arrives in Lyon",1895,"Louis Lumière","x","x"
],["The Sea",1895,"Louis Lumière","x","x"
],["The Waterer Watered",1895,"Louis Lumière","x","x"
],["A Nightmare",1896,"Georges Méliès","x","x"
],["A Terrible Night",1896,"Georges Méliès","x","x"
],["Coronation of the Emperor Nicholas the Second",1896,"Camille Cerf","x","x"
],["Coucher de la mariée",1896,"Albert Kirchner, Eugène Pirou","x","x"
],["La fée aux choux",1896,"Alice Guy","x","x"
],["Saut à la couverte",1896,"","x","x"
],["The Arrival of a Train",1896,"Auguste Lumière, Louis Lumière","x","x"
],["The Conjuring of a Woman at the House of Robert Houdin",1896,"Georges Méliès","x","x"
],["The House of the Devil",1896,"Georges Méliès","x","x"
],["The Kiss",1896,"William Heise","x","x"
],["The Messers. Lumière at Cards",1896,"Louis Lumière","x","x"
],["After the Ball, the Bath",1897,"Georges Méliès","x","x"
],["Rapunzel",1897,"Oskar Messter","x","x"
],["Riña en un café",1897,"Fructuós Gelabert","x","x"
],["The Devil's Castle",1897,"Georges Méliès","x","x"
],["An Execution by Hanging",1898,"","x","x"
],["Four Heads Are Better Than One",1898,"Georges Méliès","x","x"
],["Something Good - Negro Kiss",1898,"William Nicholas Selig","x","x"
],["The Astronomer's Dream; or, the Man in the Moon",1898,"Georges Méliès","x","x"
],["The Humpty Dumpty Circus",1898,"J. Stuart Blackton, Albert E. Smith","x","x"
],["The Temptation of St. Anthony",1898,"Georges Méliès","x","x"
],["A Gay Old Boy",1899,"Wallace McCutcheon","x","x"
],["An Extraordinary Wrestling Match",1899,"Georges Méliès","x","x"
],["Cinderella",1899,"Georges Méliès","x","x"
],["Haggard's She: The Pillar of Fire",1899,"Georges Méliès","x","x"
],["King John",1899,"Walter Pfeffer Dando, William K.L. Dickson, Herbert Beerbohm Tree","x","x"
],["The Dairy Maid's Revenge",1899,"","x","x"
],["The Sign of the Cross",1899,"Georges Méliès","x","x"
] ];
console.table(data);
let content = "";
for (let i = 0; i < data.length; i++) {
  if (data[i][3] != "") {content +=
    '<div>' +
      '<img src="' + data[i][4] + '">' +
      '<section>' +
        '<p>' + data[i][0] + '</p>' +
        '<p>' + data[i][1] + '</p>' +
        '<p>' + data[i][2] + '</p>' +
        '<a href="https://www.google.com/search?q=' + data[i][0] + ' (' + data[i][1] + ') Wikipedia" target="_blank">Google</a><br>' +
        '<a href="' + data[i][3] + '" target="_blank">Wikipedia</a>' +
      '</section>' +
    '</div>';
  }
}
document.getElementById("body").innerHTML = content;
